---
- name: upstart service
  become: true
  template:
    src: "node_exporter.upstart.j2"
    dest: "/etc/init/node_exporter.conf"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - restart node_exporter
