---
- name: sysvinit service
  become: true
  template:
    src: "node_exporter.sysvinit.j2"
    dest: "/etc/init.d/node_exporter"
    owner: root
    group: root
    mode: "u=rwx,go=rx"
  notify:
    - restart node_exporter
